services:
  mongo:
    image: mongo:7
    container_name: aws-employee-mgmt-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: emp
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro

volumes:
  mongo_data:
